- name: install apache
  ansible.builtin.apt:
    name: apache2
    state: present
  notify:
    -checking status

- name: config index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: start apache
  ansible.builtin.service:
    name: apache2
    state: started 
    enabled: true
  notify:
    -checking status

- name: copy conf file
  ansible.builtin.copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
  notify:
    - restart apache
    - checking status
